# Generated by Django 4.2.11 on 2024-04-13 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_userclass_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userclass',
            name='profile_picture',
        ),
    ]
