# Generated by Django 4.2.11 on 2024-04-13 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_remove_userclass_profile_picture'),
    ]

    operations = [
    ]
