# Generated by Django 4.2.11 on 2024-04-13 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0004_auto_20240413_1553'),
    ]

    operations = [
    ]
