# Generated by Django 4.2.11 on 2024-04-14 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0007_request_user_alter_request_target_broadcast'),
    ]

    operations = [
        migrations.RenameField(
            model_name='broadcast',
            old_name='date_of_Broadacast',
            new_name='date_of_Broadcast',
        ),
    ]
