# Generated by Django 4.2.11 on 2024-04-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0009_rename_date_of_broadcast_broadcast_date_of_broadcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclass',
            name='coins',
            field=models.IntegerField(default=0),
        ),
    ]
