# Generated by Django 4.2.11 on 2024-04-19 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0010_userclass_coins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userclass',
            name='coins',
        ),
    ]
