# Generated by Django 4.2.11 on 2024-04-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0011_remove_userclass_coins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broadcast_enabled', models.BooleanField(default=True)),
                ('api_usage_enabled', models.BooleanField(default=True)),
                ('registration_enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
