# Generated by Django 4.2.11 on 2024-04-20 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0012_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HoneyPotLoginAttempt',
        ),
    ]
