# Generated by Django 4.2.11 on 2024-04-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0013_delete_honeypotloginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='room_id',
            field=models.CharField(default='room_0af9c7ea-8a58-4caa-8b94-b07aa3c98741', max_length=150),
            preserve_default=False,
        ),
    ]
