# Generated by Django 4.2.11 on 2024-04-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0014_bot_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
    ]
