# Generated by Django 4.2.11 on 2024-04-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0015_bot_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='is_being_used',
            field=models.BooleanField(default=True),
        ),
    ]
