# Generated by Django 4.2.11 on 2024-04-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0016_bot_is_being_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
